name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Setup go-chglog
        working-directory: /tmp
        env:
          VERSION: "0.10.0"
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v${VERSION}/git-chglog_${VERSION}_linux_amd64.tar.gz
          gunzip git-chglog_${VERSION}_linux_amd64.tar.gz
          tar -xvf git-chglog_${VERSION}_linux_amd64.tar
          sudo mv git-chglog /usr/local/bin/

      - name: Generate changelog
        run: git-chglog -c .github/git-chlog/config.yaml -o RELEASE_CHANGELOG.md $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body_path: RELEASE_CHANGELOG.md
